### ISSUE TITLE
storekit UI testing

### ISSUE THREAD

**Issue by dimirey** [silvansky/BelkaChipher#1]
Hi silvansky,

I saw your post on stackoverflow regarding [how to run UI tests utilizing a storekit config](https://stackoverflow.com/questions/63923508/skproductsrequest-fails-in-xcode-12-gm-in-ui-tests-and-sktestsession/63941381#63941381).

I'm attempting to implement this but so far have only gotten unit tests working with the storekit config. Is it possible to get your guidance on getting this to work?

Best,
Dimitri

**Comment by silvansky** [comment]
Hi!

Not sure this repo is a good place to talk, but anyway...

For now few things are broken in Xcode 12.2 (see https://stackoverflow.com/questions/64916130/skreceiptrefreshrequest-always-fails-in-xcode-12-2-with-storekit-configuration/ ), so there is no way to test IAPs in Simulator because receipt cannot be refreshed.

Also, maybe this question might help you: https://stackoverflow.com/questions/63923508/skproductsrequest-fails-in-xcode-12-gm-in-ui-tests-and-sktestsession

**Comment by dimirey** [comment]
yeah agreed this isn't the best place to talk but github nor stackoverflow allow direct messages. thank you for you response!
